
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Mar 09 20:50:19 CST 2017
//----------------------------------------------------

package com.CompiladorGraphik.Gramaticas;

import java.io.*;
import java_cup.runtime.*;
import java.util.ArrayList;

/** CUP v0.10k generated parser.
  * @version Thu Mar 09 20:50:19 CST 2017
  */
public class analisis_sintactico extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public analisis_sintactico() {super();}

  /** Constructor which sets the default scanner. */
  public analisis_sintactico(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\071\000\002\002\004\000\002\003\003\000\002\004" +
    "\004\000\002\004\003\000\002\004\003\000\002\005\005" +
    "\000\002\005\006\000\002\005\005\000\002\005\006\000" +
    "\002\006\011\000\002\006\010\000\002\006\007\000\002" +
    "\006\006\000\002\007\003\000\002\007\003\000\002\007" +
    "\003\000\002\010\004\000\002\010\003\000\002\011\004" +
    "\000\002\011\004\000\002\011\004\000\002\011\004\000" +
    "\002\011\003\000\002\047\005\000\002\051\005\000\002" +
    "\052\005\000\002\057\005\000\002\057\003\000\002\060" +
    "\003\000\002\060\005\000\002\036\005\000\002\036\003" +
    "\000\002\012\007\000\002\012\005\000\002\056\010\000" +
    "\002\056\006\000\002\042\005\000\002\042\006\000\002" +
    "\040\003\000\002\040\003\000\002\040\003\000\002\040" +
    "\003\000\002\040\003\000\002\041\005\000\002\041\003" +
    "\000\002\050\005\000\002\050\005\000\002\050\005\000" +
    "\002\050\005\000\002\050\005\000\002\050\005\000\002" +
    "\050\004\000\002\050\003\000\002\050\003\000\002\050" +
    "\003\000\002\050\003\000\002\050\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\145\000\010\055\011\057\010\105\006\001\002\000" +
    "\012\002\ufffe\055\011\057\142\105\141\001\002\000\004" +
    "\002\000\001\002\000\004\005\137\001\002\000\004\002" +
    "\136\001\002\000\004\005\134\001\002\000\004\005\013" +
    "\001\002\000\004\002\ufffd\001\002\000\006\022\015\025" +
    "\014\001\002\000\010\046\101\047\076\050\077\001\002" +
    "\000\006\023\016\061\026\001\002\000\004\002\ufff5\001" +
    "\002\000\006\017\113\035\112\001\002\000\004\035\111" +
    "\001\002\000\006\017\107\035\106\001\002\000\006\023" +
    "\104\061\026\001\002\000\006\023\ufff0\061\ufff0\001\002" +
    "\000\004\035\103\001\002\000\006\023\uffeb\061\uffeb\001" +
    "\002\000\014\006\034\051\030\052\027\053\032\054\031" +
    "\001\002\000\004\005\uffd9\001\002\000\004\005\uffdb\001" +
    "\002\000\004\005\uffda\001\002\000\004\005\uffd7\001\002" +
    "\000\004\005\036\001\002\000\004\005\uffd8\001\002\000" +
    "\014\017\uffe0\020\042\024\041\025\037\035\uffe0\001\002" +
    "\000\014\017\uffd5\020\uffd5\024\uffd5\025\uffd5\035\uffd5\001" +
    "\002\000\010\046\101\047\076\050\077\001\002\000\012" +
    "\017\uffde\020\073\025\072\035\uffde\001\002\000\004\005" +
    "\071\001\002\000\020\004\043\005\045\006\052\011\047" +
    "\014\051\044\044\045\050\001\002\000\026\010\uffcd\011" +
    "\uffcd\012\uffcd\013\uffcd\015\uffcd\016\uffcd\021\uffcd\023\uffcd" +
    "\024\uffcd\035\uffcd\001\002\000\026\010\uffc9\011\uffc9\012" +
    "\uffc9\013\uffc9\015\uffc9\016\uffc9\021\uffc9\023\uffc9\024\uffc9" +
    "\035\uffc9\001\002\000\026\010\uffcc\011\uffcc\012\uffcc\013" +
    "\uffcc\015\uffcc\016\uffcc\021\uffcc\023\uffcc\024\uffcc\035\uffcc" +
    "\001\002\000\016\010\056\011\060\012\054\013\061\015" +
    "\057\021\070\001\002\000\020\004\043\005\045\006\052" +
    "\011\047\014\051\044\044\045\050\001\002\000\026\010" +
    "\uffca\011\uffca\012\uffca\013\uffca\015\uffca\016\uffca\021\uffca" +
    "\023\uffca\024\uffca\035\uffca\001\002\000\020\004\043\005" +
    "\045\006\052\011\047\014\051\044\044\045\050\001\002" +
    "\000\026\010\uffcb\011\uffcb\012\uffcb\013\uffcb\015\uffcb\016" +
    "\uffcb\021\uffcb\023\uffcb\024\uffcb\035\uffcb\001\002\000\016" +
    "\010\056\011\060\012\054\013\061\015\057\016\055\001" +
    "\002\000\020\004\043\005\045\006\052\011\047\014\051" +
    "\044\044\045\050\001\002\000\026\010\uffcf\011\uffcf\012" +
    "\uffcf\013\uffcf\015\uffcf\016\uffcf\021\uffcf\023\uffcf\024\uffcf" +
    "\035\uffcf\001\002\000\020\004\043\005\045\006\052\011" +
    "\047\014\051\044\044\045\050\001\002\000\020\004\043" +
    "\005\045\006\052\011\047\014\051\044\044\045\050\001" +
    "\002\000\020\004\043\005\045\006\052\011\047\014\051" +
    "\044\044\045\050\001\002\000\020\004\043\005\045\006" +
    "\052\011\047\014\051\044\044\045\050\001\002\000\026" +
    "\010\uffd1\011\uffd1\012\uffd1\013\uffd1\015\057\016\uffd1\021" +
    "\uffd1\023\uffd1\024\uffd1\035\uffd1\001\002\000\026\010\uffd3" +
    "\011\uffd3\012\054\013\061\015\057\016\uffd3\021\uffd3\023" +
    "\uffd3\024\uffd3\035\uffd3\001\002\000\026\010\uffd0\011\uffd0" +
    "\012\uffd0\013\uffd0\015\uffd0\016\uffd0\021\uffd0\023\uffd0\024" +
    "\uffd0\035\uffd0\001\002\000\026\010\uffd4\011\uffd4\012\054" +
    "\013\061\015\057\016\uffd4\021\uffd4\023\uffd4\024\uffd4\035" +
    "\uffd4\001\002\000\026\010\uffd2\011\uffd2\012\uffd2\013\uffd2" +
    "\015\057\016\uffd2\021\uffd2\023\uffd2\024\uffd2\035\uffd2\001" +
    "\002\000\026\010\uffce\011\uffce\012\054\013\061\015\057" +
    "\016\uffce\021\uffce\023\uffce\024\uffce\035\uffce\001\002\000" +
    "\012\017\uffdd\020\uffdd\025\uffdd\035\uffdd\001\002\000\014" +
    "\017\uffd6\020\uffd6\024\uffd6\025\uffd6\035\uffd6\001\002\000" +
    "\010\046\101\047\076\050\077\001\002\000\020\004\043" +
    "\005\045\006\052\011\047\014\051\044\044\045\050\001" +
    "\002\000\016\010\056\011\060\012\054\013\061\015\057" +
    "\021\075\001\002\000\012\017\uffdc\020\uffdc\025\uffdc\035" +
    "\uffdc\001\002\000\010\017\ufff4\022\ufff4\035\ufff4\001\002" +
    "\000\010\017\ufff3\022\ufff3\035\ufff3\001\002\000\006\017" +
    "\uffdf\035\uffdf\001\002\000\010\017\ufff2\022\ufff2\035\ufff2" +
    "\001\002\000\006\017\uffe1\035\uffe1\001\002\000\006\023" +
    "\uffec\061\uffec\001\002\000\004\002\ufff6\001\002\000\006" +
    "\023\ufff1\061\ufff1\001\002\000\006\023\uffef\061\uffef\001" +
    "\002\000\020\004\043\005\045\006\052\011\047\014\051" +
    "\044\044\045\050\001\002\000\016\010\056\011\060\012" +
    "\054\013\061\015\057\035\uffea\001\002\000\006\023\uffed" +
    "\061\uffed\001\002\000\006\023\uffee\061\uffee\001\002\000" +
    "\004\022\114\001\002\000\022\004\043\005\045\006\052" +
    "\011\047\014\051\022\116\044\044\045\050\001\002\000" +
    "\004\035\uffe9\001\002\000\022\004\043\005\045\006\052" +
    "\011\047\014\051\022\116\044\044\045\050\001\002\000" +
    "\006\023\uffe6\024\uffe6\001\002\000\006\023\122\024\123" +
    "\001\002\000\020\010\056\011\060\012\054\013\061\015" +
    "\057\023\uffe5\024\uffe5\001\002\000\004\035\uffe8\001\002" +
    "\000\022\004\043\005\045\006\052\011\047\014\051\022" +
    "\116\044\044\045\050\001\002\000\006\023\uffe7\024\uffe7" +
    "\001\002\000\006\023\126\024\123\001\002\000\006\023" +
    "\uffe4\024\uffe4\001\002\000\004\022\130\001\002\000\006" +
    "\023\131\061\026\001\002\000\004\002\ufff7\001\002\000" +
    "\006\023\133\061\026\001\002\000\004\002\ufff8\001\002" +
    "\000\004\035\135\001\002\000\012\002\ufffa\055\ufffa\057" +
    "\ufffa\105\ufffa\001\002\000\004\002\001\001\002\000\004" +
    "\035\140\001\002\000\012\002\ufffc\055\ufffc\057\ufffc\105" +
    "\ufffc\001\002\000\004\005\146\001\002\000\004\005\144" +
    "\001\002\000\004\002\uffff\001\002\000\004\035\145\001" +
    "\002\000\012\002\ufff9\055\ufff9\057\ufff9\105\ufff9\001\002" +
    "\000\004\035\147\001\002\000\012\002\ufffb\055\ufffb\057" +
    "\ufffb\105\ufffb\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\145\000\012\003\006\004\004\005\003\006\011\001" +
    "\001\000\004\006\142\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\007\126" +
    "\001\001\000\020\010\021\011\022\012\020\023\024\047" +
    "\017\051\023\056\016\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\016\011" +
    "\104\012\020\023\024\047\017\051\023\056\016\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\040\032\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\041\034\001" +
    "\001\000\002\001\001\000\004\042\037\001\001\000\002" +
    "\001\001\000\004\007\101\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\050\045\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\050\066\001\001\000\002\001\001\000\004\050\052" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\050" +
    "\065\001\001\000\002\001\001\000\004\050\064\001\001" +
    "\000\004\050\063\001\001\000\004\050\062\001\001\000" +
    "\004\050\061\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\007\077\001\001\000\004\050\073\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\050\107\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\052\114\001\001" +
    "\000\010\050\120\057\117\060\116\001\001\000\002\001" +
    "\001\000\010\050\120\057\124\060\116\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\050\120\060\123\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\020\010\131\011\022\012\020\023\024\047\017\051\023" +
    "\056\016\001\001\000\002\001\001\000\016\011\104\012" +
    "\020\023\024\047\017\051\023\056\016\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$analisis_sintactico$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$analisis_sintactico$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$analisis_sintactico$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




 String expresion="";
// METODOS Y VARIABLES GLOBALES DEL PARSER, PUEDEN SER PUBLICAS O PRIVADAS

   
  
    public void syntax_error(Symbol s){
        /**Metodo al que se llama automaticamente ante algun error sintactico.*/
        System.out.println("Error Sintactico en la Linea " + (s.right+1) +" Columna "+s.left+ ". token " +s.value + " no reconocido." );
    }
             
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{
        /**Metodo al que se llama en el momento en que ya no es posible una recuperacion de errores.*/
        System.out.println("Error Sintactico en la Linea imposible recuperar " + (s.right+1)+ " Columna "+s.left+". token " + s.value + " no reconocido.");
    }




}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$analisis_sintactico$actions {


//METODOS Y VARIABLES QUE SOLO PUEDEN SER ACCEDIDAS DENTRO DEL PARSER https://github.com/Esvux/MakerC3D
 

  private final analisis_sintactico parser;

  /** Constructor */
  CUP$analisis_sintactico$actions(analisis_sintactico parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$analisis_sintactico$do_action(
    int                        CUP$analisis_sintactico$act_num,
    java_cup.runtime.lr_parser CUP$analisis_sintactico$parser,
    java.util.Stack            CUP$analisis_sintactico$stack,
    int                        CUP$analisis_sintactico$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$analisis_sintactico$result;

      /* select the action based on the action number */
      switch (CUP$analisis_sintactico$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // EXP ::= verdadero 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(38/*EXP*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // EXP ::= falso 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(38/*EXP*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // EXP ::= caracter 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(38/*EXP*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // EXP ::= identificador 
            {
              Object RESULT = null;
		System.out.println("identificador");
              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(38/*EXP*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // EXP ::= numero 
            {
              Object RESULT = null;
		System.out.println("numero");
              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(38/*EXP*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // EXP ::= menos EXP 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(38/*EXP*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-1)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // EXP ::= parea EXP parec 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(38/*EXP*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // EXP ::= EXP eleva EXP 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(38/*EXP*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // EXP ::= EXP div EXP 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(38/*EXP*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // EXP ::= EXP por EXP 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(38/*EXP*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // EXP ::= EXP menos EXP 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(38/*EXP*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // EXP ::= EXP mas EXP 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(38/*EXP*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // IDS ::= identificador 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(31/*IDS*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // IDS ::= IDS coma identificador 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(31/*IDS*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // TIPO ::= bool 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(30/*TIPO*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // TIPO ::= caracter 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(30/*TIPO*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // TIPO ::= decimal 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(30/*TIPO*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // TIPO ::= cadena 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(30/*TIPO*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // TIPO ::= entero 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(30/*TIPO*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // DIMENSION ::= DIMENSION corcha EXP corchc 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(32/*DIMENSION*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-3)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // DIMENSION ::= corcha EXP corchc 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(32/*DIMENSION*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // DECLARARARREGLOBAL ::= var TIPO IDS DIMENSION 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(44/*DECLARARARREGLOBAL*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-3)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // DECLARARARREGLOBAL ::= var TIPO IDS DIMENSION dosp VISIBILIDAD 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(44/*DECLARARARREGLOBAL*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-5)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // DECLARARVARGLOBAL ::= var TIPO IDS 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(8/*DECLARARVARGLOBAL*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // DECLARARVARGLOBAL ::= var TIPO IDS dosp VISIBILIDAD 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(8/*DECLARARVARGLOBAL*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-4)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // PARAMETRO ::= EXP 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(28/*PARAMETRO*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // PARAMETRO ::= PARAMETRO coma EXP 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(28/*PARAMETRO*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // ARREGLOMASIGNAR2 ::= llv1 ARREGLOMASIGNAR1 llv2 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(46/*ARREGLOMASIGNAR2*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // ARREGLOMASIGNAR2 ::= EXP 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(46/*ARREGLOMASIGNAR2*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // ARREGLOMASIGNAR1 ::= ARREGLOMASIGNAR2 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(45/*ARREGLOMASIGNAR1*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // ARREGLOMASIGNAR1 ::= ARREGLOMASIGNAR1 coma ARREGLOMASIGNAR2 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(45/*ARREGLOMASIGNAR1*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // ARREGLOMASIGNAR ::= llv1 ARREGLOMASIGNAR1 llv2 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(40/*ARREGLOMASIGNAR*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // DECLARARARREGLOASIGNAR ::= DECLARARARREGLOBAL igual ARREGLOMASIGNAR 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(39/*DECLARARARREGLOASIGNAR*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // DECLARARVARGLOBALASIGNAR ::= DECLARARVARGLOBAL igual EXP 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(37/*DECLARARVARGLOBALASIGNAR*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // CUERPO1 ::= DELCARARFUNCION 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(7/*CUERPO1*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // CUERPO1 ::= DECLARARARREGLOASIGNAR finexp 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(7/*CUERPO1*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-1)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // CUERPO1 ::= DECLARARVARGLOBALASIGNAR finexp 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(7/*CUERPO1*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-1)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // CUERPO1 ::= DECLARARARREGLOBAL finexp 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(7/*CUERPO1*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-1)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // CUERPO1 ::= DECLARARVARGLOBAL finexp 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(7/*CUERPO1*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-1)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // CUERPO ::= CUERPO1 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(6/*CUERPO*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // CUERPO ::= CUERPO CUERPO1 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(6/*CUERPO*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-1)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // VISIBILIDAD ::= publico 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(5/*VISIBILIDAD*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // VISIBILIDAD ::= privado 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(5/*VISIBILIDAD*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // VISIBILIDAD ::= protegido 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(5/*VISIBILIDAD*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // CLASE ::= als identificador llv1 llv2 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(4/*CLASE*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-3)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // CLASE ::= als identificador llv1 CUERPO llv2 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(4/*CLASE*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-4)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // CLASE ::= als identificador dosp VISIBILIDAD llv1 llv2 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(4/*CLASE*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-5)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // CLASE ::= als identificador dosp VISIBILIDAD llv1 CUERPO llv2 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(4/*CLASE*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-6)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // ENCABEZADO ::= ENCABEZADO importar identificador finexp 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(3/*ENCABEZADO*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-3)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // ENCABEZADO ::= importar identificador finexp 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(3/*ENCABEZADO*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // ENCABEZADO ::= ENCABEZADO incluir_HK identificador finexp 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(3/*ENCABEZADO*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-3)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // ENCABEZADO ::= incluir_HK identificador finexp 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(3/*ENCABEZADO*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-2)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // GRAPHICK ::= CLASE 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(2/*GRAPHICK*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // GRAPHICK ::= ENCABEZADO 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(2/*GRAPHICK*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // GRAPHICK ::= ENCABEZADO CLASE 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(2/*GRAPHICK*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-1)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= GRAPHICK 
            {
              Object RESULT = null;

              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(1/*INICIO*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          return CUP$analisis_sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-1)).value;
		RESULT = start_val;
              CUP$analisis_sintactico$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-1)).left, ((java_cup.runtime.Symbol)CUP$analisis_sintactico$stack.elementAt(CUP$analisis_sintactico$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$analisis_sintactico$parser.done_parsing();
          return CUP$analisis_sintactico$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

