
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Mar 09 20:50:19 CST 2017
//----------------------------------------------------

package com.CompiladorGraphik.Gramaticas;

/** CUP generated class containing symbol constants. */
public class simbolo {
  /* terminals */
  public static final int xorr = 22;
  public static final int continuar = 59;
  public static final int bool = 41;
  public static final int finexp = 27;
  public static final int corchc = 15;
  public static final int corcha = 14;
  public static final int imprimir = 66;
  public static final int dondeCadena = 64;
  public static final int coma = 18;
  public static final int igual = 13;
  public static final int nott = 24;
  public static final int identificador = 3;
  public static final int inicio = 69;
  public static final int als = 43;
  public static final int caracter = 4;
  public static final int mayorque = 28;
  public static final int menorIgual = 31;
  public static final int dondeTodo = 65;
  public static final int menosmenos = 26;
  public static final int si = 51;
  public static final int mientras = 57;
  public static final int andd = 23;
  public static final int importar = 45;
  public static final int numero = 2;
  public static final int masmas = 25;
  public static final int protegido = 37;
  public static final int menos = 7;
  public static final int columna = 61;
  public static final int eleva = 11;
  public static final int var = 47;
  public static final int hereda = 46;
  public static final int EOF = 0;
  public static final int dosp = 19;
  public static final int mas = 6;
  public static final int noIgual = 33;
  public static final int para = 56;
  public static final int llamar = 50;
  public static final int mayorIgual = 30;
  public static final int verdadero = 34;
  public static final int procesar = 62;
  public static final int publico = 36;
  public static final int error = 1;
  public static final int nuevo = 48;
  public static final int ndecimal = 5;
  public static final int expresion = 68;
  public static final int entero = 39;
  public static final int por = 8;
  public static final int vacio = 44;
  public static final int menorque = 29;
  public static final int falso = 35;
  public static final int caso = 54;
  public static final int hacer = 58;
  public static final int orr = 21;
  public static final int graphikar_funcion = 70;
  public static final int donde = 63;
  public static final int privado = 38;
  public static final int llv2 = 17;
  public static final int igualIgual = 32;
  public static final int llv1 = 16;
  public static final int puntocoma = 20;
  public static final int incluir_HK = 67;
  public static final int terminar = 60;
  public static final int retornar = 49;
  public static final int div = 9;
  public static final int dedefecto = 55;
  public static final int selecciona = 53;
  public static final int decimal = 40;
  public static final int parec = 12;
  public static final int sino = 52;
  public static final int cadena = 42;
  public static final int parea = 10;
}

