
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Mar 12 22:53:14 CST 2017
//----------------------------------------------------

package com.CompiladorHaskellPlusPlus.Gramaticas;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int decc = 18;
  public static final int igualigual = 38;
  public static final int corchc = 14;
  public static final int corcha = 13;
  public static final int mod = 6;
  public static final int par = 26;
  public static final int asc = 27;
  public static final int coma = 34;
  public static final int igual = 37;
  public static final int entonces = 33;
  public static final int t_else = 35;
  public static final int identificador = 48;
  public static final int calcular = 16;
  public static final int let = 12;
  public static final int succ = 17;
  public static final int mayorque = 43;
  public static final int menorIgual = 42;
  public static final int end = 36;
  public static final int sum = 22;
  public static final int si = 32;
  public static final int length = 29;
  public static final int andd = 46;
  public static final int masmas = 53;
  public static final int max = 20;
  public static final int menos = 3;
  public static final int porcentaje = 15;
  public static final int dosp = 39;
  public static final int EOF = 0;
  public static final int parc = 10;
  public static final int mas = 2;
  public static final int mayorIgual = 44;
  public static final int revers = 24;
  public static final int para = 9;
  public static final int error = 1;
  public static final int ndecimal = 50;
  public static final int pot = 8;
  public static final int por = 4;
  public static final int menorque = 41;
  public static final int sqrt = 7;
  public static final int product = 23;
  public static final int caso = 40;
  public static final int impr = 25;
  public static final int orr = 47;
  public static final int desc = 28;
  public static final int llv2 = 31;
  public static final int diferente = 45;
  public static final int llv1 = 30;
  public static final int dolar = 11;
  public static final int admiracionadmiracion = 21;
  public static final int div = 5;
  public static final int num = 49;
  public static final int min = 19;
  public static final int cadena = 51;
  public static final int tchar = 52;
}

