/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package idecompi2_proyecto1;


import Archivos.Archivo;
import com.CompiladorGraphik.Gramaticas.analisis_lexico;

import com.CompiladorGraphik.Gramaticas.analisis_sintactico;
import com.ParserTree.Graficar;

import java.awt.Color;
import java.io.IOException;
import java.io.StringReader;
import java.util.Arrays;
import jaco.swing.autocomplete.Autocomplete;


import java.util.logging.Level;
import java.util.logging.Logger;
import java_cup.runtime.Symbol;



import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.xml.transform.Source;



/**
 *
 * @author chato
 */
public class Vista extends javax.swing.JFrame {
    


    /**
     * Creates new form Vista
     */
    public Vista() {
        
       
        initComponents();
        aparieciawindows();
       this.setLocationRelativeTo(null);
    }
    
    public void aparieciawindows() {
        
        try {
            JFrame.setDefaultLookAndFeelDecorated(true);
            JDialog.setDefaultLookAndFeelDecorated(true);
            // UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
            //UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.motif.MotifLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jBcompilar = new javax.swing.JButton();
        jBanalizar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTextconsola = new javax.swing.JTextArea();
        cargarArticulo = new javax.swing.JButton();
        jpestania = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextIDE = new javax.swing.JTextPane(new EstiloDocuments(Color.BLUE,Color.ORANGE,Color.GREEN,Color.GRAY,true));
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBcompilar.setBackground(new java.awt.Color(0, 204, 51));
        jBcompilar.setText("compilar");
        jBcompilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcompilarActionPerformed(evt);
            }
        });

        jBanalizar.setBackground(new java.awt.Color(255, 153, 0));
        jBanalizar.setText("analizar");
        jBanalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBanalizarActionPerformed(evt);
            }
        });

        jButton1.setText("archivo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        JTextconsola.setColumns(20);
        JTextconsola.setRows(5);
        jScrollPane1.setViewportView(JTextconsola);

        cargarArticulo.setText("Articulo");
        cargarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarArticuloActionPerformed(evt);
            }
        });

        jTextIDE.setText("ALS identificador : protegido{\n" +

            "}");
        jScrollPane2.setViewportView(jTextIDE);

        jpestania.addTab("tab1", jScrollPane2);

        jMenu1.setText("File");

        jMenuItem1.setText("Abrir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Guardar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Guardar Como");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem4.setText("Nueva Pestaña");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Borrar Pestaña Actual");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("compialador");

        jMenuItem6.setText("compilar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
                    .addComponent(jpestania))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jBanalizar)
                    .addComponent(jBcompilar)
                    .addComponent(cargarArticulo))
                .addGap(11, 11, 11))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(169, 169, 169)
                        .addComponent(cargarArticulo)
                        .addGap(18, 18, 18)
                        .addComponent(jBcompilar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jBanalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpestania, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBcompilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcompilarActionPerformed

    }//GEN-LAST:event_jBcompilarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBanalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBanalizarActionPerformed

//aqui tomo el texto pero de la pesta~a


//        javax.swing.JScrollPane scrol = (javax.swing.JScrollPane) this.jpestania.getSelectedComponent();  
//        javax.swing.JTextPane tex =(javax.swing.JTextPane) scrol.getViewport().getComponent(0);
//        AnalizaTexto(tex.getText());


        javax.swing.JScrollPane scrol = (javax.swing.JScrollPane) this.jpestania.getSelectedComponent();  
        javax.swing.JTextPane tex =(javax.swing.JTextPane) scrol.getViewport().getComponent(0);
        AnalizaTexto2(tex.getText());
    }//GEN-LAST:event_jBanalizarActionPerformed

    private void cargarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarArticuloActionPerformed
        

    }//GEN-LAST:event_cargarArticuloActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Archivo archivo = new Archivo();
        archivo.abrirArchivo();
        
        
        try {
     
            javax.swing.JScrollPane scrol = (javax.swing.JScrollPane) this.jpestania.getSelectedComponent();            
            javax.swing.JTextPane tex =(javax.swing.JTextPane) scrol.getViewport().getComponent(0);
            tex.setText(archivo.getContenido());
            this.jpestania.setTitleAt(jpestania.getSelectedIndex(), archivo.getArchivo().getPath());
            
            
        } catch (IOException ex) {
            System.out.println("no se abrio archivo");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        try {
            Archivo archivo = new Archivo();
            archivo.guardarArchivo(this.jTextIDE.getText());
        } catch (IOException ex) {
            Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        
        /// esto efunciona para crear una nueva pesta~a
        String [] nombredelArra = {"sd 1234", "if ( int x = 0 : x>10 : ++ ) { \n \n } "}; 
        
        Autocomplete completar = new Autocomplete (Arrays.asList(nombredelArra),true);
        completar.setMinimumPrefixLength(1);
        completar.setMaximumRowCount(10);
       
        
        javax.swing.JTextPane jTextIDE = new javax.swing.JTextPane
         /*esta linea de codigo pela es para pintar ()*/(new EstiloDocuments(Color.BLUE,Color.ORANGE,Color.GREEN,Color.GRAY,true));
        completar.setTextComponent(jTextIDE);
        javax.swing.JScrollPane jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane2.setViewportView(jTextIDE);
        jpestania.addTab("nueva"+this.jpestania.getTabCount(), jScrollPane2);
       
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
     
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
    
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea JTextconsola;
    private javax.swing.JButton cargarArticulo;
    private javax.swing.JButton jBanalizar;
    private javax.swing.JButton jBcompilar;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextIDE;
    private javax.swing.JTabbedPane jpestania;
    // End of variables declaration//GEN-END:variables

     public void AnalizaTexto(String texto) {
        StringReader miReader = new StringReader(texto);
        analisis_lexico miAnalizador = new analisis_lexico(miReader);
        analisis_sintactico parser = new analisis_sintactico(miAnalizador);
        
        try {
            
            parser.parse();
            
            System.out.println("Analisis terminado");
           
        } catch (Exception E) {
            System.out.println(E);
            
            System.out.println("Error parser");
        }
        
        try {
            Symbol s = (Symbol) miAnalizador.next_token();
            
            while (s.sym != 0) {
                System.out.println("Lexema: " + s.value + "     " + "Token: " + s.sym);
                s = (Symbol) miAnalizador.next_token();
                //System.out.println(Ltoken.TokenPalabra);
            }
            
        } catch (Exception E) {
            
            System.out.println("error simbolo" + E);
        }
    }

     
public void AnalizaTexto2(String texto) {
        StringReader miReader = new StringReader(texto);
        com.CompiladorHaskellPlusPlus.Gramaticas.AnalisisLexico miAnalizador =     
             new com.CompiladorHaskellPlusPlus.Gramaticas.AnalisisLexico(miReader);
        com.CompiladorHaskellPlusPlus.Gramaticas.Analisis_Sintactico parser 
                = new com.CompiladorHaskellPlusPlus.Gramaticas.Analisis_Sintactico(miAnalizador);
        
        try {
          parser.parse();
           parser.parserTree.Arbol_listar_enlazar(parser.parserTree.root, 0);
            
           Graficar g = new Graficar();
           g.graficar(parser.parserTree);
           System.out.println("Analisis terminado ");
          
        } catch (Exception E) {
            System.out.println(E);
            
            System.out.println("Error parser");
        }
        
        try {
            Symbol s = (Symbol) miAnalizador.next_token();
            
            while (s.sym != 0) {
                System.out.println("Lexema: " + s.value + "     " + "Token: " + s.sym);
                s = (Symbol) miAnalizador.next_token();
                //System.out.println(Ltoken.TokenPalabra);
            }
            
        } catch (Exception E) {
            
            System.out.println("error simbolo" + E);
        }
    }
   
    
    public void escribirConsola(String string) {
        JTextconsola.setText(JTextconsola.getText() + string + "\n");
    }

}
